### ISSUE TITLE
Array format in GET parameter

### ISSUE THREAD

**Issue by jacobischwartz** [booqable/api-documentation#1]
Hello,

I'm testing the /orders endpoint. The by_status field is listed in the documentation as an array. What should that look like in the GET querystring? I don't see a list of field formats in the documentation.

PHP generates array querystrings as field[]=val1&field[]=val2, for example.

But when I try that format on the /orders endpoint, the statuses aren't applied to the query.

Cheers!

**Comment by Arjeno** [comment]
Hi Jacob. Looks like there is an error in the documentation, it should be `status` and not `by_status`. Could you try that? The URL should look like `?status[]=started&status[]=stopped`

**Comment by jacobischwartz** [comment]
That works, thank you!
