### ISSUE TITLE
/orders endpoint: "archived" order status not included

### ISSUE THREAD

**Issue by jacobischwartz** [booqable/api-documentation#2]
Hello,

In my testing of the /orders endpoint, the "archived" order status is not documented and also those archived orders are not included in the returned data.

I don't know if this is intentional or not, but I'm trying to access that data. It would be helpful to either clarify the situation in the negative, or make the data available and document the additional order status.

Thanks!

**Comment by Arjeno** [comment]
Archived orders are not returned by default, unless you specifically filter by it. So: `/api/1/orders?status[]=archived` will return the archived orders.

**Comment by jacobischwartz** [comment]
This was related to https://github.com/booqable/api-documentation/issues/1

Thanks for clarifying, I can now retrieve archived orders.
