### ISSUE TITLE
Add search parameters to /orders

### ISSUE THREAD

**Issue by jacobischwartz** [booqable/api-documentation#4]
Hello!

I'm trying to create a report with the API that will identify how much each item is being ordered. The report will help inform decisions about inventory management.

The issues that I'm having are:

1. I am having to individually query each order to get the lines section, rather than being able to request that section be included in the /orders endpoint. This is resulting in a very large number of API calls and a very slow report response time.
2. I only really want a subset of all orders, by date and by status: This quarter, or last year, or year to date, or year ahead, and not cancelled orders. But I am having to move through all orders, which is a very large number of results.

Are we able to get those additional parameters added? Or would you suggest that I do process things the long way and maybe break it down into batches?

Thanks,

Jacob

**Comment by jhnvz** [comment]
Hi @jacobischwartz 👋 Totally forgot to answer your question. We have undocumented endpoints which return all the data you need (historically). These endpoints are: `api/1/reports/products` and `api/1/reports/stock_items` you can use the following paramaters:
```
turnover_type: invoices|orders
range[from]: 2018-01-01T00:00:00Z
range[till]: 2018-12-31T23:59:59Z
tag[]: e-bike
tag[]: helmet
page: 1
```
If you also want this data for future orders you can apply the strategy you describe above on the orders endpoint `api/1/orders` with the following paramaters:
```
status: reserved
date[type]: query
date[starts_at][gte]: 2018-06-09T00:00:00Z
date[stops_at][lte]: 2018-06-09T23:59:59Z
```
I'd love to learn more about what you're looking to achieve as this can also benefit other customers.
